INFO - 2025-06-05 09:45:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-06-05 09:45:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-06-05 09:45:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-06-05 09:49:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-06-05 09:56:33 --> ErrorException: Undefined array key "email"
in APPPATH\Controllers\Login.php on line 176.
 1 APPPATH\Controllers\Login.php(176): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "email"', 'C:\\Proyectos\\reservalo2.0\\app\\Controllers\\Login.php', 176)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-06-05 09:57:34 --> ErrorException: Undefined array key "email"
in APPPATH\Controllers\Login.php on line 176.
 1 APPPATH\Controllers\Login.php(176): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "email"', 'C:\\Proyectos\\reservalo2.0\\app\\Controllers\\Login.php', 176)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-06-05 10:01:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-06-05 10:06:46 --> TypeError: App\Models\loginModel::anadirToken(): Argument #2 ($id_usuario) must be of type int, array given, called in C:\Proyectos\reservalo2.0\app\Controllers\Login.php on line 198
in APPPATH\Models\loginModel.php on line 143.
 1 APPPATH\Controllers\Login.php(198): App\Models\loginModel->anadirToken([...], [...])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-06-05 10:09:41 --> TypeError: App\Models\loginModel::anadirToken(): Argument #2 ($id_usuario) must be of type int, array given, called in C:\Proyectos\reservalo2.0\app\Controllers\Login.php on line 198
in APPPATH\Models\loginModel.php on line 143.
 1 APPPATH\Controllers\Login.php(198): App\Models\loginModel->anadirToken([...], [...])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-06-05 10:23:50 --> mysqli_sql_exception: Unknown column 'date_token' in 'field list' in C:\Proyectos\reservalo2.0\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Proyectos\reservalo2.0\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `usuario...', 0)
#1 C:\Proyectos\reservalo2.0\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\Proyectos\reservalo2.0\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\Proyectos\reservalo2.0\system\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\Proyectos\reservalo2.0\app\Models\loginModel.php(152): CodeIgniter\Database\BaseBuilder->update(Array)
#5 C:\Proyectos\reservalo2.0\app\Controllers\Login.php(198): App\Models\loginModel->anadirToken(Array, 5)
#6 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
#7 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Proyectos\reservalo2.0\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-06-05 10:24:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'date_token' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `token` = :token:, `date_token` = :date_token:
WHERE `id_usuario` = :id_usuario:', [...], false)
 2 APPPATH\Models\loginModel.php(152): CodeIgniter\Database\BaseBuilder->update([...])
 3 APPPATH\Controllers\Login.php(198): App\Models\loginModel->anadirToken([...], 5)
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-06-05 10:24:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'date_token' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `token` = \'4aec8a27a6977b91555977a73c4418387fb0ae25cd42805c55c4c2bdec3dac8f9487176ee5478c2dba0d7556789c51cfa672\', `date_token` = \'2025-06-05 11:23:45\'
WHERE `id_usuario` = 5')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `token` = \'4aec8a27a6977b91555977a73c4418387fb0ae25cd42805c55c4c2bdec3dac8f9487176ee5478c2dba0d7556789c51cfa672\', `date_token` = \'2025-06-05 11:23:45\'
WHERE `id_usuario` = 5')
 3 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `token` = :token:, `date_token` = :date_token:
WHERE `id_usuario` = :id_usuario:', [...], false)
 4 APPPATH\Models\loginModel.php(152): CodeIgniter\Database\BaseBuilder->update([...])
 5 APPPATH\Controllers\Login.php(198): App\Models\loginModel->anadirToken([...], 5)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-06-05 10:24:35 --> [Caused by] mysqli_sql_exception: Unknown column 'date_token' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `usuarios` SET `token` = \'4aec8a27a6977b91555977a73c4418387fb0ae25cd42805c55c4c2bdec3dac8f9487176ee5478c2dba0d7556789c51cfa672\', `date_token` = \'2025-06-05 11:23:45\'
WHERE `id_usuario` = 5', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `token` = \'4aec8a27a6977b91555977a73c4418387fb0ae25cd42805c55c4c2bdec3dac8f9487176ee5478c2dba0d7556789c51cfa672\', `date_token` = \'2025-06-05 11:23:45\'
WHERE `id_usuario` = 5')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `token` = \'4aec8a27a6977b91555977a73c4418387fb0ae25cd42805c55c4c2bdec3dac8f9487176ee5478c2dba0d7556789c51cfa672\', `date_token` = \'2025-06-05 11:23:45\'
WHERE `id_usuario` = 5')
 4 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `token` = :token:, `date_token` = :date_token:
WHERE `id_usuario` = :id_usuario:', [...], false)
 5 APPPATH\Models\loginModel.php(152): CodeIgniter\Database\BaseBuilder->update([...])
 6 APPPATH\Controllers\Login.php(198): App\Models\loginModel->anadirToken([...], 5)
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-06-05 10:48:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-06-05 10:49:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-06-05 10:49:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-06-05 10:49:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-06-05 10:49:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-06-05 10:56:06 --> ErrorException: Undefined variable $email
in APPPATH\Controllers\Login.php on line 202.
 1 APPPATH\Controllers\Login.php(202): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $email', 'C:\\Proyectos\\reservalo2.0\\app\\Controllers\\Login.php', 202)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2025-06-05 10:56:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-05 11:02:52 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): Unable to connect to smtp.gmail.com:587 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder) in C:\Proyectos\reservalo2.0\system\Email\Email.php:1897
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): Un...', 'C:\\Proyectos\\re...', 1897)
#1 C:\Proyectos\reservalo2.0\system\Email\Email.php(1897): fsockopen('smtp.gmail.com', 587, NULL, NULL, 60)
#2 C:\Proyectos\reservalo2.0\system\Email\Email.php(1810): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\Proyectos\reservalo2.0\system\Email\Email.php(1695): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\Proyectos\reservalo2.0\system\Email\Email.php(1587): CodeIgniter\Email\Email->spoolEmail()
#5 C:\Proyectos\reservalo2.0\app\Controllers\Login.php(207): CodeIgniter\Email\Email->send()
#6 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
#7 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Proyectos\reservalo2.0\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2025-06-05 11:02:52 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-06-05 11:02:52 --> 
INFO - 2025-06-05 11:05:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-05 11:05:51 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): Unable to connect to smtp.gmail.com:587 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder) in C:\Proyectos\reservalo2.0\system\Email\Email.php:1897
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): Un...', 'C:\\Proyectos\\re...', 1897)
#1 C:\Proyectos\reservalo2.0\system\Email\Email.php(1897): fsockopen('smtp.gmail.com', 587, NULL, NULL, 60)
#2 C:\Proyectos\reservalo2.0\system\Email\Email.php(1810): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\Proyectos\reservalo2.0\system\Email\Email.php(1695): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\Proyectos\reservalo2.0\system\Email\Email.php(1587): CodeIgniter\Email\Email->spoolEmail()
#5 C:\Proyectos\reservalo2.0\app\Controllers\Login.php(208): CodeIgniter\Email\Email->send()
#6 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
#7 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Proyectos\reservalo2.0\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2025-06-05 11:05:51 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-06-05 11:05:51 --> 
ERROR - 2025-06-05 11:06:26 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): Unable to connect to smtp.gmail.com:587 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder) in C:\Proyectos\reservalo2.0\system\Email\Email.php:1897
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): Un...', 'C:\\Proyectos\\re...', 1897)
#1 C:\Proyectos\reservalo2.0\system\Email\Email.php(1897): fsockopen('smtp.gmail.com', 587, NULL, NULL, 60)
#2 C:\Proyectos\reservalo2.0\system\Email\Email.php(1810): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\Proyectos\reservalo2.0\system\Email\Email.php(1695): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\Proyectos\reservalo2.0\system\Email\Email.php(1587): CodeIgniter\Email\Email->spoolEmail()
#5 C:\Proyectos\reservalo2.0\app\Controllers\Login.php(208): CodeIgniter\Email\Email->send()
#6 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
#7 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Proyectos\reservalo2.0\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2025-06-05 11:06:26 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-06-05 11:06:26 --> 
ERROR - 2025-06-05 11:19:16 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): Unable to connect to tls://smtp.gmail.com:465 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder) in C:\Proyectos\reservalo2.0\system\Email\Email.php:1897
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): Un...', 'C:\\Proyectos\\re...', 1897)
#1 C:\Proyectos\reservalo2.0\system\Email\Email.php(1897): fsockopen('tls://smtp.gmai...', 465, NULL, NULL, 60)
#2 C:\Proyectos\reservalo2.0\system\Email\Email.php(1810): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\Proyectos\reservalo2.0\system\Email\Email.php(1695): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\Proyectos\reservalo2.0\system\Email\Email.php(1587): CodeIgniter\Email\Email->spoolEmail()
#5 C:\Proyectos\reservalo2.0\app\Controllers\Login.php(208): CodeIgniter\Email\Email->send()
#6 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
#7 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Proyectos\reservalo2.0\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2025-06-05 11:19:16 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-06-05 11:19:16 --> 
ERROR - 2025-06-05 11:19:34 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): Unable to connect to tls://smtp.gmail.com:465 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder) in C:\Proyectos\reservalo2.0\system\Email\Email.php:1897
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): Un...', 'C:\\Proyectos\\re...', 1897)
#1 C:\Proyectos\reservalo2.0\system\Email\Email.php(1897): fsockopen('tls://smtp.gmai...', 465, NULL, NULL, 60)
#2 C:\Proyectos\reservalo2.0\system\Email\Email.php(1810): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\Proyectos\reservalo2.0\system\Email\Email.php(1695): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\Proyectos\reservalo2.0\system\Email\Email.php(1587): CodeIgniter\Email\Email->spoolEmail()
#5 C:\Proyectos\reservalo2.0\app\Controllers\Login.php(208): CodeIgniter\Email\Email->send()
#6 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
#7 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Proyectos\reservalo2.0\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2025-06-05 11:19:34 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-06-05 11:19:34 --> 
ERROR - 2025-06-05 11:20:44 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): Unable to connect to tls://smtp.gmail.com:465 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder) in C:\Proyectos\reservalo2.0\system\Email\Email.php:1897
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): Un...', 'C:\\Proyectos\\re...', 1897)
#1 C:\Proyectos\reservalo2.0\system\Email\Email.php(1897): fsockopen('tls://smtp.gmai...', 465, NULL, NULL, 60)
#2 C:\Proyectos\reservalo2.0\system\Email\Email.php(1810): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\Proyectos\reservalo2.0\system\Email\Email.php(1695): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\Proyectos\reservalo2.0\system\Email\Email.php(1587): CodeIgniter\Email\Email->spoolEmail()
#5 C:\Proyectos\reservalo2.0\app\Controllers\Login.php(208): CodeIgniter\Email\Email->send()
#6 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(941): App\Controllers\Login->forgotPassword()
#7 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\Proyectos\reservalo2.0\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Proyectos\reservalo2.0\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2025-06-05 11:20:44 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-06-05 11:20:44 --> 
